### ISSUE TITLE
X-Up-Location header should not be sent by default

### ISSUE THREAD

**Issue by triskweline** [jwaschkau/django-unpoly#20]
I believe this middleware automatically echoes the request URL in an `X-Up-Location` response header. I recommend not sending the `X-Up-Location` header for every request. Instead that header should only be sent if the request URL differs from the URL we want to see on the client. This may be the case if this middleware uses query parameters to preserve Unpoly headers over a reedirect.

Echoing the request URL was needed to detect the final URL after a redirect in legacy browsers, namely Internet Explorer 11. Now that IE11 is finally dead, this is no longer necessary.

Also reflecting the user-controlled request URL can lead to a [Denial of Service issue](https://github.com/unpoly/unpoly-rails/security/advisories/GHSA-m875-3xf6-mf78) in particular server setups.

Thank you for maintaining this package!

**Comment by jwaschkau** [comment]
fixed with #26
